name: TPPets
version: 2.0.0
description: Teleport pets around the map, but not in areas you don't want
load: POSTWORLD
author: GatheringExp
main: com.maxwellwheeler.plugins.tppets.TPPets
depend: [WorldEdit]
softdepend: [Vault]

commands:
  tpp:
    description: Base command for TPPets
    aliases: [teleportpets]
    usage: "Usage: /tpp [birds/dogs/cats/horses/mules/llamas/donkeys/protected/lost]"

permissions:
  tppets.*:
    description: Parent node of all tppets permissions.
    default: op
    children:
      tppets.mountother: true
      tppets.renameall: true
      tppets.allowother: true
      tppets.teleportother: true
      tppets.untameall: true
      tppets.bypassprotection: true
      tppets.bypasslimit: true
      tppets.tpanywhere: true
      tppets.rename: true
      tppets.addallow: true
      tppets.removeallow: true
      tppets.listallow: true
      tppets.protected: true
      tppets.lost: true
      tppets.dogs: true
      tppets.cats: true
      tppets.birds: true
      tppets.horses: true
      tppets.mules: true
      tppets.llamas: true
      tppets.donkeys: true

  tppets.teleport:
    description: Parent node of tppets teleporting permissions.
    default: true
    children:
      tppets.dogs: true
      tppets.cats: true
      tppets.birds: true
      tppets.horses: true
      tppets.mules: true
      tppets.llamas: true
      tppets.donkeys: true

  # Admin management permissions
  tppets.mountother:
    default: op
    description: Allows user to mount and use inventories of pets that do not belong to them.
  tppets.renameall:
    default: op
    description: Allows user to rename pets that do not belong to them.
  tppets.allowother:
    default: op
    description: Allows user to /tpp allow, /tpp remove, and /tpp list as if they were other players.
  tppets.teleportother:
    default: op
    description: Allows user to teleport pets owned by someone else to their location.
  tppets.untameall:
    default: op
    description: Allows user to untame pets that they don't own.
  tppets.bypassprotection:
    default: op
    description: Allows user to damage pets that they don't own.
  tppets.bypasslimit:
    default: op
    description: Allows user to tame pets past the pet taming limit.
  tppets.tpanywhere:
    default: op
    description: Allows user to teleport pets into, and keep pets inside, protected regions.

  # Player management permissions
  tppets.rename:
    default: true
    description: Allows user to rename their pets.
  tppets.addallow:
    default: true
    description: Allows user to allow other users to their pets.
  tppets.removeallow:
    default: true
    description: Allows user to disallow other users to their pets.
  tppets.listallow:
    default: true
    description: Allows user to list players that are allowed to a pet.

  # Region commands
  tppets.protected:
    default: op
    description: Allows user to set cuboid regions where pets are not allowed.
  tppets.lost:
    default: op
    description: Allows user to set cuboid regions where pets found in protected regions are sent.

  # Teleportation commands
  tppets.dogs:
    default: true
    description: Allows user to teleport their dogs to them.
  tppets.cats:
    default: true
    description: Allows user to teleport their cats to them.
  tppets.birds:
    default: true
    description: Allows user to teleport their birds to them.
  tppets.horses:
    default: true
    description: Allows user to teleport their horses to them.
  tppets.mules:
    default: true
    description: Allows user to teleport their mules to them.
  tppets.llamas:
    default: true
    description: Allows user to teleport their llamas to them.
  tppets.donkeys:
    default: true
    description: Allows user to teleport their donkeys to them.

