package com.maxwellwheeler.plugins.tppets.commands;

public enum CommandStatus {
    SUCCESS, INVALID_SENDER, INSUFFICIENT_PERMISSIONS, NO_PLAYER, SYNTAX_ERROR, NO_PET, NO_PET_TYPE, DB_FAIL, CANT_TELEPORT, CANT_TELEPORT_IN_PR, NO_TARGET_PLAYER, NO_TARGET_PET, ALREADY_DONE, INVALID_NAME, INVALID_LR_NAME, INVALID_PR_NAME, INVALID_MESSAGE, LIMIT_REACHED, PET_NAME_ALREADY_IN_USE, NO_REGION
}
