package com.maxwellwheeler.plugins.tppets.commands;

public enum CommandStatus {
    SUCCESS, INVALID_SENDER, INSUFFICIENT_PERMISSIONS, NO_PLAYER, SYNTAX_ERROR, NO_PET, NO_PET_TYPE, DB_FAIL, CANT_TELEPORT, CANT_TELEPORT_IN_PR, NO_TARGET_PLAYER, ALREADY_DONE, INVALID_NAME, LIMIT_REACHED
}
