package com.maxwellwheeler.plugins.tppets.commands;

/**
 * Enum representing all command status states for all commands.
 */
public enum CommandStatus {
    SUCCESS, INVALID_SENDER, INSUFFICIENT_PERMISSIONS, NO_PLAYER, SYNTAX_ERROR, NO_PET, NO_ENTITY, NO_PET_TYPE, DB_FAIL, CANT_TELEPORT, CANT_TELEPORT_IN_PR, NO_TARGET_PLAYER, ALREADY_DONE, INVALID_NAME, INVALID_LR_NAME, INVALID_PR_NAME, INVALID_MESSAGE, LIMIT_REACHED, NO_REGION, TP_BETWEEN_WORLDS, NOT_ENABLED
}
